---
- name: Get vars from planning
  include_vars:
    file: "{{ installer_base_dir }}/planning.json"
    name: planning_vars

- name: Set facts from planning.json
  set_fact:
    ip_list: "{{ planning_vars.clusters.split(',') }}"
    leading_server: "{{ planning_vars.leading_server }}"
    leading_server_hostname: "{{ ansible_hostname }}"
    password: "{{ planning_vars.password }}"

- name: Set facts for installer
  set_fact:
    master_nodes: "{{ ip_list[0:3] }}"
