---
- hosts: localhost
  any_errors_fatal: true
  name: Setup ssh tunnel and prepare cluster hosts config
  roles:
    - { role: ssh_tunnel, tags: ssh_tunnel }
    - { role: inventory, tags: inventory }
