# all these nodes will be added into k8s cluster. The first three nodes with master role
"clusters": "192.168.155.111,192.168.155.112,192.168.155.113,192.168.155.114"

# which node should the playbook should be run
"leading_server": "192.168.155.111"

# password for ips in clusters
"password": "12345"
